export const initialMessages = [
  {
    id: 1,
    contactId: 1,
    content: "Hey, how are you?",
    sender: "them",
    timestamp: "10:00 AM",
    status: "read",
  },
  {
    id: 2,
    contactId: 1,
    content: "I'm good, thanks! How about you?",
    sender: "me",
    timestamp: "10:05 AM",
    status: "read",
  },
  {
    id: 3,
    contactId: 2,
    content: "See you tomorrow!",
    sender: "them",
    timestamp: "11:00 AM",
    status: "delivered",
  },
  {
    id: 4,
    contactId: 2,
    content: "Looking forward to it!",
    sender: "me",
    timestamp: "11:10 AM",
    status: "delivered",
  },
  {
    id: 5,
    contactId: 3,
    content: "Let's catch up soon!",
    sender: "them",
    timestamp: "12:00 PM",
    status: "sent",
  },
  {
    id: 6,
    contactId: 3,
    content: "Definitely, when are you free?",
    sender: "me",
    timestamp: "12:15 PM",
    status: "sent",
  },
  {
    id: 7,
    contactId: 4,
    content: "Got the files, thanks!",
    sender: "them",
    timestamp: "01:00 PM",
    status: "read",
  },
  {
    id: 8,
    contactId: 4,
    content: "You're welcome!",
    sender: "me",
    timestamp: "01:05 PM",
    status: "read",
  },
  {
    id: 9,
    contactId: 5,
    content: "Happy Birthday!",
    sender: "them",
    timestamp: "02:00 PM",
    status: "read",
  },
  {
    id: 10,
    contactId: 5,
    content: "Thank you so much!",
    sender: "me",
    timestamp: "02:10 PM",
    status: "read",
  },
  {
    id: 11,
    contactId: 6,
    content: "Can we reschedule?",
    sender: "them",
    timestamp: "03:00 PM",
    status: "delivered",
  },
  {
    id: 12,
    contactId: 6,
    content: "Sure, let me know when works.",
    sender: "me",
    timestamp: "03:05 PM",
    status: "delivered",
  },
  {
    id: 13,
    contactId: 7,
    content: "I'm on my way.",
    sender: "them",
    timestamp: "04:00 PM",
    status: "read",
  },
  {
    id: 14,
    contactId: 7,
    content: "See you soon!",
    sender: "me",
    timestamp: "04:05 PM",
    status: "read",
  },
  {
    id: 15,
    contactId: 8,
    content: "Lunch at 12?",
    sender: "them",
    timestamp: "05:00 PM",
    status: "sent",
  },
  {
    id: 16,
    contactId: 8,
    content: "Sounds good to me.",
    sender: "me",
    timestamp: "05:10 PM",
    status: "sent",
  },
  {
    id: 17,
    contactId: 9,
    content: "Check your email.",
    sender: "them",
    timestamp: "06:00 PM",
    status: "read",
  },
  {
    id: 18,
    contactId: 9,
    content: "Just did, thanks!",
    sender: "me",
    timestamp: "06:10 PM",
    status: "read",
  },
  {
    id: 19,
    contactId: 10,
    content: "Call me when free.",
    sender: "them",
    timestamp: "07:00 PM",
    status: "delivered",
  },
  {
    id: 20,
    contactId: 10,
    content: "Will do. Talk soon.",
    sender: "me",
    timestamp: "07:15 PM",
    status: "delivered",
  },
];

export const initialContacts = [
  {
    id: 1,
    name: "John Doe",
    avatar: "https://picsum.photos/id/1001/200",
    lastMessage: "Hey, how are you?",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 2,
    name: "Jane Smith",
    avatar: "https://picsum.photos/id/1002/200",
    lastMessage: "See you tomorrow!",
    lastMessageStatus: "delivered",
    unreadCount: 1,
  },
  {
    id: 3,
    name: "Alice Johnson",
    avatar: "https://picsum.photos/id/1003/200",
    lastMessage: "Let's catch up soon!",
    lastMessageStatus: "sent",
    unreadCount: 2,
  },
  {
    id: 4,
    name: "Bob Brown",
    avatar: "https://picsum.photos/id/1004/200",
    lastMessage: "Got the files, thanks!",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 5,
    name: "Charlie Davis",
    avatar: "https://picsum.photos/id/1005/200",
    lastMessage: "Happy Birthday!",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 6,
    name: "Diana Wilson",
    avatar: "https://picsum.photos/id/1006/200",
    lastMessage: "Can we reschedule?",
    lastMessageStatus: "delivered",
    unreadCount: 1,
  },
  {
    id: 7,
    name: "Edward Harris",
    avatar: "https://picsum.photos/id/1020/200",
    lastMessage: "I'm on my way.",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 8,
    name: "Fiona Clark",
    avatar: "https://picsum.photos/id/1008/200",
    lastMessage: "Lunch at 12?",
    lastMessageStatus: "sent",
    unreadCount: 1,
  },
  {
    id: 9,
    name: "George Lewis",
    avatar: "https://picsum.photos/id/1009/200",
    lastMessage: "Check your email.",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 10,
    name: "Hannah Lee",
    avatar: "https://picsum.photos/id/1010/200",
    lastMessage: "Call me when free.",
    lastMessageStatus: "delivered",
    unreadCount: 1,
  },
  {
    id: 11,
    name: "Ian Walker",
    avatar: "https://picsum.photos/id/1011/200",
    lastMessage: "Meeting tomorrow?",
    lastMessageStatus: "sent",
    unreadCount: 2,
  },
  {
    id: 12,
    name: "Jackie Martin",
    avatar: "https://picsum.photos/id/1012/200",
    lastMessage: "Need your feedback.",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 13,
    name: "Kevin Adams",
    avatar: "https://picsum.photos/id/1013/200",
    lastMessage: "Will be late.",
    lastMessageStatus: "delivered",
    unreadCount: 1,
  },
  {
    id: 14,
    name: "Laura Thompson",
    avatar: "https://picsum.photos/id/1014/200",
    lastMessage: "Thanks for your help!",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 15,
    name: "Mike Scott",
    avatar: "https://picsum.photos/id/1015/200",
    lastMessage: "Let's do it again!",
    lastMessageStatus: "sent",
    unreadCount: 2,
  },
  {
    id: 16,
    name: "Nina Robinson",
    avatar: "https://picsum.photos/id/1016/200",
    lastMessage: "Are you free later?",
    lastMessageStatus: "read",
    unreadCount: 1,
  },
  {
    id: 17,
    name: "Oliver Green",
    avatar: "https://picsum.photos/id/1010/200",
    lastMessage: "Send me the link.",
    lastMessageStatus: "delivered",
    unreadCount: 2,
  },
  {
    id: 18,
    name: "Paula Adams",
    avatar: "https://picsum.photos/id/1018/200",
    lastMessage: "Good to hear from you!",
    lastMessageStatus: "sent",
    unreadCount: 0,
  },
  {
    id: 19,
    name: "Quincy Young",
    avatar: "https://picsum.photos/id/1019/200",
    lastMessage: "Did you see that?",
    lastMessageStatus: "read",
    unreadCount: 0,
  },
  {
    id: 20,
    name: "Rachel White",
    avatar: "https://picsum.photos/id/1020/200",
    lastMessage: "Let's meet up.",
    lastMessageStatus: "delivered",
    unreadCount: 1,
  },
];
